# Generated by Django 5.2.8 on 2025-11-13 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacion',
            options={'ordering': ['date', 'time'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mensaje de Contacto', 'verbose_name_plural': 'Mensajes de Contacto'},
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Notas internas'),
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('completed', 'Completada')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aplicacion',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas del cliente'),
        ),
        migrations.AlterField(
            model_name='aplicacion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AvailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_appointments', models.IntegerField(default=1, help_text='Máximo de citas por slot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horario Disponible',
                'verbose_name_plural': 'Horarios Disponibles',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
